version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://root:root@db:5432/my_database
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - flask_network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    networks:
      - flask_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  flask_network:
    driver: bridge

volumes:
  postgres_data:
